CREATE DATABASE IF NOT EXISTS restaurante_michin
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE restaurante_michin;

CREATE TABLE IF NOT EXISTS pedidos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    nombre VARCHAR(150) NOT NULL,
    telefono VARCHAR(30) NOT NULL,
    direccion VARCHAR(250) NOT NULL,
    observaciones VARCHAR(500) NULL,

    sopa VARCHAR(150) NULL,
    plato VARCHAR(150) NULL,
    bebida VARCHAR(150) NULL,
    postre VARCHAR(150) NULL,
    adicional VARCHAR(150) NULL,

    total DECIMAL(12,2) NOT NULL,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
